mod; DD.MM.YYYY;HH:MM:SS;aligned
src; "IVU.plan -> VDV-Schnittstelle"; "23.10.2014"; "18:22:35"
chs; "ISO8859-1"
ver; "3.4.0.0"
ifv; "1.10"
dve; "1"
fft; ""
tbl; MENGE_FAHRTART
atr; BASIS_VERSION; FAHRTART_NR; STR_FAHRTART
frm; num[9.0]; num[2.0]; char[6]
rec;         1;  1; "L     "
rec;         1;  2; "E     "
rec;         1;  3; "A     "
rec;         1;  4; "B     "
end; 4
eof; 1