mod; DD.MM.YYYY;HH:MM:SS;aligned
src; "IVU.plan -> VDV-Schnittstelle"; "23.10.2014"; "18:22:36"
chs; "ISO8859-1"
ver; "3.4.0.0"
ifv; "1.10"
dve; "1"
fft; ""
tbl; MENGE_ORT_TYP
atr; BASIS_VERSION; ORT_TYP_NR; ORT_TYP_TEXT
frm; num[9.0]; num[2.0]; char[40]
rec;         1;  1; "Haltestelle                             "
rec;         1;  2; "Betriebshof                             "
rec;         1;  3; "Betriebsstelle                          "
end; 3
eof; 1