mod; DD.MM.YYYY;HH:MM:SS;aligned
src; "IVU.plan -> VDV-Schnittstelle"; "23.10.2014"; "18:22:37"
chs; "ISO8859-1"
ver; "3.4.0.0"
ifv; "1.10"
dve; "1"
fft; ""
tbl; MENGE_LEISTUNGSART
atr; BASIS_VERSION; LEISTUNGSART_NR; LEISTUNGSART_TEXT
frm; num[9.0]; num[9.0]; char[10]
rec;         1;         1; "LINEA     "
rec;         1;         2; "BIS       "
rec;         1;         4; "SCOL      "
end; 3
eof; 1