mod; DD.MM.YYYY;HH:MM:SS;aligned
src; "IVU.plan -> VDV-Schnittstelle"; "23.10.2014"; "18:22:37"
chs; "ISO8859-1"
ver; "3.4.0.0"
ifv; "1.10"
dve; "1"
fft; ""
tbl; MENGE_FZG_TYP
atr; BASIS_VERSION; FZG_TYP_NR; FZG_LAENGE; FZG_TYP_SITZ; FZG_TYP_STEH; FZG_TYP_TEXT; SONDER_PLATZ; STR_FZG_TYP
frm; num[9.0]; num[4.0]; num[3.0]; num[4.0]; num[4.0]; char[40]; num[4.0]; char[6]
rec;         1;    1;   0;    0;    0; "S                                       ";    0; "S     "
end; 1
eof; 1