mod; DD.MM.YYYY;HH:MM:SS;aligned
src; "IVU.plan -> VDV-Schnittstelle"; "23.10.2014"; "18:22:31"
chs; "ISO8859-1"
ver; "3.4.0.0"
ifv; "1.10"
dve; "1"
fft; ""
tbl; PERSONAL
atr; FAHRER_NR; PERSONAL_NAME; PERSONAL_VORNAME; PERSONAL_KENNUNG; AUSBILDUNG; PERSONAL_STRASSE; PERSONAL_WOHNORT; PERSONAL_PRIVAT_TELEFON; PERSONAL_MOBIL_TELEFON
frm; num[5.0]; char[40]; char[40]; char[40]; char[6]; char[40]; char[40]; char[40]; char[40]
end; 0
eof; 1