mod; DD.MM.YYYY;HH:MM:SS;aligned
src; "IVU.plan -> VDV-Schnittstelle"; "23.10.2014"; "18:22:31"
chs; "ISO8859-1"
ver; "3.4.0.0"
ifv; "1.10"
dve; "1"
fft; ""
tbl; REC_UMS
atr; BASIS_VERSION; EINAN_NR; TAGESART_NR; UMS_BEGINN; UMS_ENDE; UMS_MIN; UMS_MAX; UMAX_VERZ_MAN; UMAX_VERZ_AUTO
frm; num[9.0]; num[5.0]; num[6.0]; num[6.0]; num[6.0]; num[5.0]; num[5.0]; num[5.0]; num[5.0]
end; 0
eof; 1