mod; DD.MM.YYYY;HH:MM:SS;aligned
src; "IVU.plan -> VDV-Schnittstelle"; "23.10.2014"; "18:22:35"
chs; "ISO8859-1"
ver; "3.4.0.0"
ifv; "1.10"
dve; "1"
fft; ""
tbl; REC_SEL_ZP
atr; BASIS_VERSION; BEREICH_NR; ONR_TYP_NR; ORT_NR; SEL_ZIEL; SEL_ZIEL_TYP; ZP_ONR; ZP_TYP; SEL_ZP_LAENGE; ZP_LFD_NR
frm; num[9.0]; num[3.0]; num[2.0]; num[9.0]; num[9.0]; num[2.0]; num[9.0]; num[2.0]; num[6.0]; num[4.0]
end; 0
eof; 1