mod; DD.MM.YYYY;HH:MM:SS;aligned
src; "IVU.plan -> VDV-Schnittstelle"; "23.10.2014"; "18:21:59"
chs; "ISO8859-1"
ver; "3.4.0.0"
ifv; "1.10"
dve; "1"
fft; ""
tbl; REC_UMLAUF
atr; BASIS_VERSION; TAGESART_NR; UM_UID; ANF_ORT; ANF_ONR_TYP; END_ORT; END_ONR_TYP; FZG_TYP_NR; UM_UID_EXTERN; BHOF_ORT_NR
frm; num[9.0]; num[6.0]; num[8.0]; num[9.0]; num[2.0]; num[9.0]; num[2.0]; num[4.0]; char[30]; num[9.0]
end; 0
eof; 1