mod; DD.MM.YYYY;HH:MM:SS;aligned
src; "IVU.plan -> VDV-Schnittstelle"; "23.10.2014"; "18:22:31"
chs; "ISO8859-1"
ver; "3.4.0.0"
ifv; "1.10"
dve; "1"
fft; ""
tbl; ZUORDNUNG_ANWESENHEIT_FAHRER
atr; FAHRER_ANWESENHEIT_NR; FAHRER_NR; KALENDERDATUM_VON; UHRZEIT_VON; KALENDERDATUM_BIS; UHRZEIT_BIS; ANWESENHEIT_NR
frm; num[9.0]; num[5.0]; num[8.0]; num[6.0]; num[8.0]; num[6.0]; num[5.0]
end; 0
eof; 1